const items = [
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIWSxSCc_JxBcK52Vrcv1AwS3IeYC_3gAMag&s',
      company: 'Carlton London',
      item_name: 'Rhodium-Plated CZ Floral Studs',
      original_price: 1045,
      current_price: 606,
      discount_percentage: 42,
      return_period: 14,
      rating: {
          stars: 4.5,
          count: 1400,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3_KSJivsAI3tsl245X9KwcmYRIB84qPO85Q&s',
      company: 'CUKOO',
      item_name: 'Women Padded Halter Neck Swimming Dress',
      original_price: 2599,
      current_price: 1507,
      discount_percentage: 42,
      return_period: 14,
      rating: {
          stars: 4.3,
          count: 24,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfSc4WQNsgz113DldmPwKCmorUSGY6Tuc-5A&s',
      company: 'NUEVOSDAMAS',
      item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
      original_price: 1599,
      current_price: 495,
      discount_percentage: 69,
      return_period: 14,
      rating: {
          stars: 4.1,
          count: 249,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNozqpJc3UOaqO5Bme-TwDM-KAGTE5UMkGEQ&s',
      company: 'ADIDAS',
      item_name: 'Indian Cricket ODI Jersey',
      original_price: 999,
      current_price: 999,
      discount_percentage: 0,
      return_period: 14,
      rating: {
          stars: 5.0,
          count: 10,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWe_qNpTXFB4wfby-6NaCocqffWy6bXqgBqg&s',
      company: 'Roadster',
      item_name: 'Pure Cotton T-shirt',
      original_price: 1399,
      current_price: 489,
      discount_percentage: 65,
      return_period: 14,
      rating: {
          stars: 4.2,
          count: 3500,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8rWEU-OM5O-jeIdkcXPBVZJE7md-cEbOEww&s',
      company: 'Nike',
      item_name: 'Men ReactX Running Shoes',
      original_price: 14995,
      current_price: 14995,
      discount_percentage: 0,
      return_period: 14,
      rating: {
          stars: 0.0,
          count: 0,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSvu2hHeYdMfoS1ykNkA8Q_SFmIZoBLLg4Eg&s',
      company: 'The Indian Garage Co',
      item_name: 'Men Slim Fit Regular Shorts',
      original_price: 1599,
      current_price: 639,
      discount_percentage: 60,
      return_period: 14,
      rating: {
          stars: 4.2,
          count: 388,
      },
  },
  {
      image: 'https://images.apollo247.in/pub/media/catalog/product/n/i/niv0123_2_1.jpg?tr=q-80,f-webp,w-400,dpr-3,c-at_max%20400w',
      company: 'Nivea',
      item_name: 'Men Fresh Deodrant 150ml',
      original_price: 285,
      current_price: 142,
      discount_percentage: 50,
      return_period: 14,
      rating: {
          stars: 4.2,
          count: 5200,
      },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ8LFxqKBiSNh4YypqrHet5-IvgTW6nkW8ig&s',
      company: 'Rice Bran',
      item_name: 'Mustard Oil',
      original_price: 170,
      current_price: 136,
      discount_percentage: 20,
      return_period: 14,
      rating: {
          stars: 4.2,
          count: 5200,
  },
},
{
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpysxbIzCJfS6jVXpjEsCRhfHocCuuvuuwOg&s',
    company: 'Ponds',
    item_name: 'LUXURY Collection',
    original_price: 450,
    current_price: 360,
    discount_percentage: 20,
    return_period: 14,
    rating: {
        stars: 4.2,
        count: 5200,
},
},
{
      image: 'https://5.imimg.com/data5/SELLER/Default/2024/7/436561860/ZH/KP/KJ/163043379/71n-a7ubwnl-sx679-500x500.jpg',
      company: 'PUMA',
      item_name: 'REB Mens Jersy',
      original_price: 450,
      current_price: 360,
      discount_percentage: 20,
      return_period: 14,
      rating: {
          stars: 4.2,
          count: 5200,
  },
  },
  {
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGNgKdn391LH5aLudC5RRCYxyYUrQ1aXp2ng&s',
      company: 'Himalaya',
      item_name: 'Sanitizer',
      original_price: 450,
      current_price: 360,
      discount_percentage: 20,
      return_period: 14,
      rating: {
          stars: 4.5,
          count: 5300,
  },
    },
];
module.exports = items;